[project]
name = "agent-docexpert"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncio>=3.4.3",
    "chromadb>=0.6.3",
    "crawl4ai>=0.4.248",
]
