[project]
name = "agent-docexpert"
version = "0.0.1"
description = "Technical documentation Q&A agent workflow"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "argparse>=1.4.0",
    "asyncio>=3.4.3",
    "chromadb>=0.6.3",
    "crawl4ai>=0.4.248",
]
